version: '3.8'
services:
  security-service:
    build: .
    container_name:  security-service
    ports:
      - "8080:8080"
    depends_on:
      - security-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://security-db:5432/jwt-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  security-db:
    image: postgres:14-alpine
    container_name: security-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=jwt-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root